spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/emi_db
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.hikari.initialization-fail-timeout=0
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
server.port=8088